# Generated by Django 5.2.1 on 2025-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=17, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('leida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('numero_control', models.CharField(blank=True, max_length=20, null=True)),
                ('id_grupo', models.IntegerField(blank=True, db_column='id_grupp', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('horas_semana', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('presente', models.IntegerField(blank=True, null=True)),
                ('justificante', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('perfil_egreso', models.TextField(blank=True, null=True)),
                ('plan_estudios_documento', models.TextField(blank=True, null=True)),
                ('mapa_curricular', models.TextField(blank=True, null=True)),
                ('vigente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('numero_trabajador', models.CharField(blank=True, max_length=20, null=True)),
                ('disponibilidad', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
            ],
            options={
                'db_table': 'docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.AutoField(db_column='id_grupp', primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(blank=True, db_column='nombre_grupp', max_length=50, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=9, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
    ]
